"use client";
/**
 * DeliverablesTabs.tsx
 * Owner: Omkar25-source
 *
 * Tabbed view of the four deliverable panels generated by the
 * agent pipeline: PRD, Tech Specs, Marketing, and Sprint Board.
 * Accepts raw agent output objects and renders them with markdown-
 * aware formatting.
 */

import { useState } from "react";

// ── Types ─────────────────────────────────────────────────────────────────────
export type AgentOutputs = {
  product_manager?:     Record<string, unknown>;
  architect?:           Record<string, unknown>;
  marketing?:           Record<string, unknown>;
  engineering_manager?: Record<string, unknown>;
};

type Tab = {
  id:    string;
  label: string;
  agent: keyof AgentOutputs;
};

const TABS: Tab[] = [
  { id: "prd",      label: "■ PRD",          agent: "product_manager"     },
  { id: "tech",     label: "■ Tech Specs",   agent: "architect"           },
  { id: "marketing",label: "■ Marketing",    agent: "marketing"           },
  { id: "sprint",   label: "■ Sprint Board", agent: "engineering_manager" },
];

// ── Helpers ───────────────────────────────────────────────────────────────────
function renderValue(value: unknown, depth = 0): JSX.Element {
  if (value === null || value === undefined) {
    return <span style={{ color: "var(--text-secondary, #a1a1aa)" }}>—</span>;
  }
  if (typeof value === "string") {
    return (
      <p style={{ margin: "0 0 6px", color: "var(--text-primary, #e2e8f0)", lineHeight: 1.65 }}>
        {value}
      </p>
    );
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return (
      <span style={{ color: "var(--accent-cyan, #22d3ee)", fontFamily: "var(--font-mono, monospace)" }}>
        {String(value)}
      </span>
    );
  }
  if (Array.isArray(value)) {
    return (
      <ul style={{ margin: "4px 0 8px", paddingLeft: "18px", listStyle: "none" }}>
        {value.map((item, i) => (
          <li key={i} style={{ marginBottom: "4px", display: "flex", gap: "8px" }}>
            <span style={{ color: "var(--accent, #a78bfa)", flexShrink: 0, marginTop: "1px" }}>◆</span>
            <span>{renderValue(item, depth + 1)}</span>
          </li>
        ))}
      </ul>
    );
  }
  if (typeof value === "object") {
    return (
      <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
        {Object.entries(value as Record<string, unknown>).map(([k, v]) => (
          <div key={k}>
            <p
              style={{
                margin: "0 0 4px",
                fontSize: "0.72rem",
                textTransform: "uppercase",
                letterSpacing: "0.07em",
                fontWeight: 700,
                color: "var(--text-secondary, #a1a1aa)",
              }}
            >
              {k.replace(/_/g, " ")}
            </p>
            {renderValue(v, depth + 1)}
          </div>
        ))}
      </div>
    );
  }
  return <span>{String(value)}</span>;
}

// ── Component ─────────────────────────────────────────────────────────────────
type Props = {
  outputs: AgentOutputs;
};

export function DeliverablesTabs({ outputs }: Props) {
  const [active, setActive] = useState<string>(TABS[0].id);
  const activeTab  = TABS.find((t) => t.id === active)!;
  const activeData = outputs[activeTab.agent];

  return (
    <div
      style={{
        borderRadius: "16px",
        overflow: "hidden",
        border: "1px solid rgba(255,255,255,0.08)",
        background: "rgba(255,255,255,0.03)",
        backdropFilter: "blur(24px)",
        WebkitBackdropFilter: "blur(24px)",
      }}
    >
      {/* Tab strip */}
      <div
        style={{
          display: "flex",
          borderBottom: "1px solid rgba(255,255,255,0.07)",
          background: "rgba(255,255,255,0.03)",
          overflowX: "auto",
        }}
      >
        {TABS.map((tab) => {
          const isActive  = tab.id === active;
          const hasOutput = !!outputs[tab.agent];
          return (
            <button
              key={tab.id}
              onClick={() => setActive(tab.id)}
              style={{
                flex: "1 1 0",
                padding: "11px 16px",
                background: "none",
                border: "none",
                borderBottom: isActive
                  ? "2px solid var(--accent, #a78bfa)"
                  : "2px solid transparent",
                cursor: "pointer",
                fontFamily: "var(--font-sans, sans-serif)",
                fontSize: "0.78rem",
                fontWeight: isActive ? 600 : 400,
                color: isActive
                  ? "var(--accent, #a78bfa)"
                  : hasOutput
                  ? "var(--text-primary, #e2e8f0)"
                  : "var(--text-secondary, #a1a1aa)",
                transition: "color 0.15s, border-color 0.15s",
                whiteSpace: "nowrap",
                letterSpacing: "0.02em",
              }}
            >
              {tab.label}
              {hasOutput && (
                <span
                  style={{
                    display: "inline-block",
                    marginLeft: "6px",
                    width: 5,
                    height: 5,
                    borderRadius: "50%",
                    background: "var(--accent-cyan, #22d3ee)",
                    verticalAlign: "middle",
                    boxShadow: "0 0 5px var(--accent-cyan, #22d3ee)",
                  }}
                />
              )}
            </button>
          );
        })}
      </div>

      {/* Tab content */}
      <div style={{ padding: "22px 24px", minHeight: "240px" }}>
        {activeData ? (
          renderValue(activeData)
        ) : (
          <p
            style={{
              margin: 0,
              color: "var(--text-secondary, #a1a1aa)",
              fontSize: "0.85rem",
              fontStyle: "italic",
            }}
          >
            Waiting for the {activeTab.label.replace("■ ", "")} agent to complete…
          </p>
        )}
      </div>
    </div>
  );
}
